# Generated by Django 5.2.11 on 2026-06-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=50)),
                ('task_date', models.DateField()),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('consultation', 'Consultation'), ('surgery', 'Surgery'), ('follow-up', 'Follow-up'), ('administrative', 'Administrative'), ('other', 'Other')], default='other', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctor_tasks',
                'ordering': ['task_date', 'start_time'],
            },
        ),
    ]
