# Generated by Django 5.2.11 on 2026-06-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=50, unique=True)),
                ('register_id', models.CharField(max_length=100, unique=True)),
                ('doctor_nicnumber', models.CharField(max_length=20, unique=True)),
                ('doctors_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('degrees', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('working_hospital', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'register_DoctorID',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('NIC_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('birthday', models.DateField()),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctorID', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
